### ISSUE TITLE
Figure out how to export Copay xpubkeys. 

### ISSUE THREAD

**Issue by TRhode** [DecentralVan/website#1]
See wallet.iced -- need to figure out how to get the xpubkeys out of the multisig account @findkiko

**Comment by findkiko** [comment]
Is this still open because you want to run a bitcore server locally, rather than calling out to bitpay servers? Is that what you mean by the TODO comment in the code? Or are you saying that those pubkeys in the file are just random ones and need to be replaced with our own?
